---
title: "Data Acquisition Project"
author: "Bekah Jensen"
date: "2025-11-12"
format:
  html:
    code-fold: true
    toc: true
---

```{python}
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
```

# U.S. Colleges and Graduation Rates

### An analysis of 1,000 U.S. colleges graduation rates.


## Introduction

The purpose of this blog is to show an in depth analysis of the affects on graduations rates of U.S. colleges. The analysis studies 1,000 colleges with information on student size, tuition prices, diversity, region, and graduation rates. Studying this information could be useful in determining what factors help students graduate. Those inquiring about a future college career could use the information when deciding where to attend school.

Education is crucial for societal purposes. Education allows people to become evolved thinkers, be active participants in society, and the economy. Learning what factors help students graduate could help increase overall graduation rates. While this analysis does give some insight on what influences graduation rates, this information should not be used and cited as this is not an official analysis.

## Motivation

From this analysis it is my hope that I learn more about the data cleaning process and analysis. I am hoping to gain a better understanding of demographics from different colleges across the nation.

With these goals I also hope to provide insight on the dataset created. 

## Ethical Data Practices

The data is acquired from the U.S. Census Bureau and the College Scorecard by the U.S. Department of Education.

Data gathered from the U.S. Census Bureau and College Scorecard is allowed because it is public data. Anyone can access the data as long as it is not used to identify any individual person, household, business or other entity. The Bureau also requests that the following disclaimer be made: "This product uses the Census Bureau Data API but is not endorsed or certified by the Census Bureau." 

Using these guidelines I was able to determine that use of this data for the purpose of my research question was ethical. I acquired API keys specifically assigned to myself and these keys were not published and cannot be accessed via the cleaning process and exploratory data analysis. 

## A Short Note on Acquiring the Data

This analysis uses one datasets that has been cleaned and merged from two datasets, one with information about colleges, the other about state populations. 

The <a href="https://www.census.gov/data/developers/data-sets.html">U.S. Census Bureau</a> and <a href="https://collegescorecard.ed.gov/data/api-documentation">College Scorecard</a> have in depth information about downloading data, acquiring, and use of APIs and keys. To get started follow the instructions on those sites. Once you have the two different datasets, clean them and merge to get one dataframe that includes the following columns:

- Student_Size
- Tuition_In_State
- Tuition_Out_State
- Female_Share
- Race_White
- Race_Black
- Race_Hispanic
- Race_Asian
- Race_AIAN
- Race_NHPI
- Race_Two_Or_More
- Grad_Rate
- School_Name
- City,State
- id
- July_Estimate_2024
- Region

## EDA Highlights

### Summary Statistics

```{python}
data = pd.read_csv('data/college_state_pop.csv')

data.head()

```

The table above shows the first few row of the data, this gives us an idea of what variable we are working with. For the purpose of this analysis we will be looking at what variables affect graduation rates. 
```{python}
data.describe()
```

The table above shows summary statistics for each variable in the dataframe. 

The following table is the count of N/A values after taking the averages of graduation rate, in state tuition, and out of stat tuition for each state and filling the na values with those mean values. Note there are still some unknown values for the categorical values.

| Variable             | Count |
|----------------------|--------|
| Student_Size         | 63     |
| Tuition_In_State     | 1      |
| Tuition_Out_State    | 1      |
| Female_Share         | 137    |
| Race_White           | 63     |
| Race_Black           | 63     |
| Race_Hispanic        | 63     |
| Race_Asian           | 63     |
| Race_AIAN            | 63     |
| Race_NHPI            | 63     |
| Race_Two_Or_More     | 63     |
| Grad_Rate            | 1      |
| School_Name          | 0      |
| City                 | 0      |
| State                | 0      |
| id                   | 0      |
| July_Estimate_2024   | 12     |
| Region               | 374    |

The following table is the count of occurrences for each state. Note that there is not data on all of the states in the U.S. this is due to the amount of data pulled from the API, only 1,000 schools were accounted for in the data, therefore the data will be skewed. 


| State | Count |
|--------|--------|
| AK     | 8      |
| AL     | 55     |
| AR     | 58     |
| AZ     | 40     |
| CA     | 313    |
| CO     | 51     |
| CT     | 35     |
| DC     | 12     |
| DE     | 8      |
| FL     | 122    |
| GA     | 78     |
| HI     | 12     |
| ID     | 14     |
| IL     | 156    |
| IN     | 35     |
| MN     | 1      |
| NM     | 1      |
| NY     | 1      |

There are many more schools to account for however this data is still useful. 

The data for the northern and southern regions have about the same amount of observations. 

| Region  |          |
|---------|----------|
|North    |293       |
|South    |333       | 

Next we can compute the mean graduation rate for each state in the dataset.

| State | Mean Graduation Rate |
|--------|-----------------------|
| AK     | 0.491314 |
| AL     | 0.396898 |
| AR     | 0.462617 |
| AZ     | 0.428985 |
| CA     | 0.525233 |
| CO     | 0.517437 |
| CT     | 0.625406 |
| DC     | 0.654925 |
| DE     | 0.493286 |
| FL     | 0.551218 |
| GA     | 0.435044 |
| HI     | 0.410892 |
| ID     | 0.520750 |
| IL     | 0.511828 |
| IN     | 0.534775 |
| MN     | NaN |
| NM     | 0.537000 |
| NY     | 0.125000 |

It is interesting to note that the District of Columbia, which is a territory has the highest graduation rate, with Connecticut following as a close second. Again we really can't pull reliable inferences from this since the sample sizes are skewed, especially since New York, which has some of the most prestigious universities in the country, has the lowest graduation rate and only one singular occurrence in the dataset. 


We can run a regression model on the following variables and see if any are statistically significant. 

| Term                | Coefficient          |
|----------------------|----------------------|
| **Intercept**        | 0.28883021499055983  |
| **Student_Size**     | 2.19323220e-06       |
| **Tuition_In_State** | -2.38317495e-06      |
| **Tuition_Out_State**| 1.14899535e-05       |
| **Region_numeric**   | -3.72713468e-02      |

| Metric                | Value                 |
|------------------------|-----------------------|
| **Mean Squared Error** | 0.020479592983903977  |
| **R-squared**          | 0.2711396143816296    |

We cannot pull inference from this model, however it is interesting to see if there is an interaction between certain variables.

### Plots

```{python}
sns.scatterplot(data=data, x="Tuition_In_State", y="Grad_Rate", hue="Region")
plt.xlabel('Tuition In State')
plt.ylabel('Graduation Rate')
plt.title('In State Tuition Vs. Grad Rate')
plt.grid(True)
plt.show()
```

The plot above shows in state tuition prices plotted against graduation rates, with the colors corresponding to north and south regions of the U.S. It is interesting to note that there appears to be a linear relationship between higher tuition prices and graduation rate.

```{python}
sns.scatterplot(data=data, x="Tuition_Out_State", y="Grad_Rate", hue="Region")
plt.xlabel('Tuition Out State')
plt.ylabel('Graduation Rate')
plt.title('Out of State Tuition Vs. Grad Rate')
plt.grid(True)
plt.show()
```

We can plot the the relationship between out of state tuition and graduation rates as well. From the plot we again see that there appears to be a linear relationship between the variables.

The following boxplots can help gather more inference on graduation rates for the different states. 

```{python}
# Box plots for mean graduation rate

sns.set_theme(style = "ticks")

f, ax = plt.subplots(figsize =(7,6))
ax.set_xscale("log")

sns.boxplot(
    data, x="Grad_Rate", y="State", hue = "State",
    whis=[0,10], width = .6
)

ax.xaxis.grid(True)
ax.set(ylabel="")
sns.despine(trim=True, left=True)

```

We can do the same for tuition prices, this plot uses out of state tuition data. 

```{python}
# Box plots for mean out of state tuition

sns.set_theme(style = "ticks")

f, ax = plt.subplots(figsize =(7,6))
ax.set_xscale("log")

sns.boxplot(
    data, x="Tuition_Out_State", y="State", hue = "State",
    whis=[0,10], width = .6
)

ax.xaxis.grid(True)
ax.set(ylabel="")
sns.despine(trim=True, left=True)

```

These highlights of the data help us understand that while more information and data is needed to pull reliable inferences, we can see that higher tuition prices could result in higher graduation rate in U.S. colleges.

## Resources

- <a href="https://www.census.gov/data/developers/data-sets.html">U.S. Census Bureau</a>

- <a href="https://collegescorecard.ed.gov/data/api-documentation">College Scorecard</a>

- <a href="https://www.bestcolleges.com/research/college-graduation-rates/">More information about graduation rates.</a>

## Code Links

Fork the repository below to view the code used to create and merge the datasets, as well as the EDA process.

- <a href="https://github.com/JNSREB2023/Data_Blog">Code for data analysis</a>


## Disclaimers

This product uses the Census Bureau Data API but is not endorsed or certified by the Census Bureau.

